name: dirac_operator
channels:
  - conda-forge
  - defaults
dependencies: # pkg_name=version=build
  - matplotlib=3.9.*
  - scipy=1.14.*
  - numpy
  - pip=24.2
  - hatchling=1.25.0
  - pip:
    - -e .[dev] 
